notifications:
  email: false

services:
  - docker

git:
  depth: false

env:
  jobs:
    - DOCKCROSS_IMAGE=linux-armv7       OPENBLAS_TARGET=ARMV7
    - DOCKCROSS_IMAGE=manylinux2010-x64 OPENBLAS_TARGET=NEHALEM

script:
  - export HELPER_IMAGE="${DOCKER_REGISTRY}/vosk-api-build:${DOCKCROSS_IMAGE}"
  - export VERSION="$(git describe --tags --always)"
  - export DOCKER_BUILD_ARGS="--build-arg DOCKCROSS_IMAGE=$DOCKCROSS_IMAGE --build-arg OPENBLAS_TARGET=$OPENBLAS_TARGET"
  - date; docker run --rm --privileged multiarch/qemu-user-static:register
  - date; echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # stage s1
  - date; docker pull ${HELPER_IMAGE}.s1 || true
  - date; docker build --tag ${HELPER_IMAGE}.s1 --target s1 --cache-from ${HELPER_IMAGE}.s1 ${DOCKER_BUILD_ARGS} travis
  - date; docker push ${HELPER_IMAGE}.s1
  # stage s2
  - date; docker pull ${HELPER_IMAGE}.s2 || true
  - date; docker build --tag ${HELPER_IMAGE}.s2 --target s2 --cache-from ${HELPER_IMAGE}.s1 --cache-from ${HELPER_IMAGE}.s2 ${DOCKER_BUILD_ARGS} travis
  - date; docker push ${HELPER_IMAGE}.s2
  # final stage
  - date; docker pull ${HELPER_IMAGE} || true
  - date; docker build --tag ${HELPER_IMAGE} --cache-from ${HELPER_IMAGE}.s1 --cache-from ${HELPER_IMAGE}.s2 --cache-from ${HELPER_IMAGE} ${DOCKER_BUILD_ARGS} travis
  - date; docker push ${HELPER_IMAGE}
  # build wheels
  - date; docker run --rm -v "$(pwd):/io" -e "VERSION=$VERSION" ${HELPER_IMAGE} /io/travis/build-wheels.sh

deploy:
  provider: releases
  edge: true
  token: ${GITHUB_TOKEN}
  file: wheelhouse/*
  prerelease: '[ -n "$TRAVIS_TAG" ] && echo true || echo false'
  name: "Python Binaries version=${VERSION} arch=${DOCKCROSS_IMAGE}"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|travis)$
