notifications:
  email: false

services:
  - docker

git:
  depth: false

env:
  jobs:
    - DOCKCROSS_IMAGE=linux-armv7       OPENBLAS_TARGET=ARMV7
    - DOCKCROSS_IMAGE=manylinux2010-x64 OPENBLAS_TARGET=NEHALEM

script:
  - export HELPER_IMAGE="${DOCKER_REGISTRY}/vosk-api-build:${DOCKCROSS_IMAGE}"
  - export VERSION="$(git describe --tags --always)"
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker pull $HELPER_IMAGE || true
  - date
  - docker build --cache-from $HELPER_IMAGE -t $HELPER_IMAGE --build-arg "DOCKCROSS_IMAGE=$DOCKCROSS_IMAGE" --build-arg "OPENBLAS_TARGET=$OPENBLAS_TARGET" travis
  - date
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $HELPER_IMAGE
  - date
  - docker run --rm -v "$(pwd):/io" -e "VERSION=$VERSION" $HELPER_IMAGE /io/travis/build-wheels.sh
  - date

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: wheelhouse/*
  draft: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|travis)$
