notifications:
  email: false

services:
  - docker

git:
  depth: false

os: linux # https://config.travis-ci.com/ref/os
language: shell # https://config.travis-ci.com/ref/language

env:
  jobs:
    - DOCKCROSS_IMAGE=linux-armv6       OPENBLAS_TARGET=ARMV6
    - DOCKCROSS_IMAGE=linux-armv7       OPENBLAS_TARGET=ARMV7
    - DOCKCROSS_IMAGE=manylinux2010-x64 OPENBLAS_TARGET=NEHALEM

script:
  - export HELPER_IMAGE="${DOCKER_REGISTRY}/vosk-api-build:${DOCKCROSS_IMAGE}"
  - export VERSION="$(git describe --tags --always)"
  - export DOCKER_BUILD_ARGS="--build-arg DOCKCROSS_IMAGE=$DOCKCROSS_IMAGE --build-arg OPENBLAS_TARGET=$OPENBLAS_TARGET"
  - date; docker run --rm --privileged multiarch/qemu-user-static:register
  - date; echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # stage s1
  - date; docker pull ${HELPER_IMAGE}.s1 || true
  - date; docker build --tag ${HELPER_IMAGE}.s1 --target s1 --cache-from ${HELPER_IMAGE}.s1 ${DOCKER_BUILD_ARGS} travis
  - date; docker push ${HELPER_IMAGE}.s1
  # stage s2
  - date; docker pull ${HELPER_IMAGE}.s2 || true
  - date; docker build --tag ${HELPER_IMAGE}.s2 --target s2 --cache-from ${HELPER_IMAGE}.s1 --cache-from ${HELPER_IMAGE}.s2 ${DOCKER_BUILD_ARGS} travis
  - date; docker push ${HELPER_IMAGE}.s2
  # final stage
  - date; docker pull ${HELPER_IMAGE} || true
  - date; docker build --tag ${HELPER_IMAGE} --cache-from ${HELPER_IMAGE}.s1 --cache-from ${HELPER_IMAGE}.s2 --cache-from ${HELPER_IMAGE} ${DOCKER_BUILD_ARGS} travis
  - date; docker push ${HELPER_IMAGE}
  # build wheels
  - date; docker run --rm -v "$(pwd):/io" -e "VERSION=$VERSION" ${HELPER_IMAGE} /io/travis/build-wheels.sh

deploy:
  # Draft a GitHib Release for each commit
  # https://docs.travis-ci.com/user/deployment-v2/providers/releases/
  - provider: releases
    edge: true
    token: $GITHUB_TOKEN
    file: wheelhouse/*
    draft: true
    name: $VERSION
    tag_name: $TRAVIS_TAG
    on:
      all_branches: true
      condition: $GITHUB_TOKEN
  # Upload to PyPI when building a tagged commit
  # https://docs.travis-ci.com/user/deployment-v2/providers/script/
  # https://pypi.org/project/twine/
  - provider: script
    edge: true
    script: bash -c "sudo apt-get update && sudo apt-get install -y python3-pip && python3 -m pip install twine && python3 -m twine check wheelhouse/* && python3 -m twine upload wheelhouse/*"
    on:
      all_branches: true
      condition: $TRAVIS_TAG && $TWINE_USERNAME && $TWINE_PASSWORD
